title:            NodeSchool Vancouver
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
url:              //nodeschool.io/vancouver
# url:              //localhost:4000


# http://jekyllrb.com/docs/permalinks/
permalink:   /:categories/:title/
